First Release PR - Pacvar
nf-core/pacvar pull request #4
Opened 2024-11-15 18:47 UTC by tanyasarkjain

## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [x] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/pacvar/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, also make a PR on the nf-core/pacvar _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [x] Make sure your code lints (`nf-core lint`).
- [x] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [x] Check for unexpected warnings in debug mode (`nextflow run . -profile debug,test,docker --outdir <OUTDIR>`).
- [x] Usage Documentation in `docs/usage.md` is updated.
- [x] Output Documentation in `docs/output.md` is updated.
- [x] `CHANGELOG.md` is updated.
- [x] `README.md` is updated (including new tool citations and authors/contributors).

2024-11-21 07:53 UTC, fellen31 reviewed
Nice, I started going the code, but are you committing directly to dev? Has anyone reviewed any bits of this code before?

2024-11-21 07:53 UTC, fellen31 commented on README.md
> +![nf-core/rnaseq metro map](docs/images/metro_update_w_tabix_orange.svg)
```suggestion
![nf-core/pacvar metro map](docs/images/metro_update_w_tabix_orange.svg)
```

2024-11-21 07:53 UTC, fellen31 commented on README.md
> +![nf-core/rnaseq metro map](docs/images/metro_update_w_tabix_orange.svg)
Also, could there be a dark-mode metro map with white background instead of transparent?

2024-11-21 07:53 UTC, fellen31 commented on README.md
> +3. Sort and Index alignments ([`SAMtools`](https://sourceforge.net/projects/samtools/files/samtools/))
```suggestion
3. Sort and index alignments ([`SAMtools`](https://sourceforge.net/projects/samtools/files/samtools/))
```

2024-11-21 07:53 UTC, fellen31 commented on README.md
>  4. Phase SNPS, SVs and BAM files ([`hiphase`](https://github.com/PacificBiosciences/HiPhase))
```suggestion
4. Phase SNPs, SVs and BAM files ([`hiphase`](https://github.com/PacificBiosciences/HiPhase))
```

2024-11-21 07:53 UTC, fellen31 commented on README.md
> +   --outdir <OUTDIR>
Duplicate `--outdir`

2024-11-21 07:53 UTC, fellen31 commented on README.md
> +optional paramaters include: --skip_demultiplexing, --skip_snp --skip_sv --skip_phase
```suggestion
optional paramaters include: --skip_demultiplexing, --skip_snp, --skip_sv, --skip_phase
```

2024-11-21 07:53 UTC, fellen31 commented on assets/schema_input.json
> +                "errorMessage": "Tumor BAM or CRAM file cannot contain spaces and must have extension '.bam' or '.cram'",
Does it have to be a tumor file?

2024-11-21 07:53 UTC, fellen31 commented on assets/schema_input.json
> +                "errorMessage": "Tumor BAI or CRAI index file cannot contain spaces and must have extension '.bai' or '.crai'",
Does it have to be a tumor file?

2024-11-21 07:53 UTC, fellen31 commented on assets/schema_input.json
> +                "errorMessage": "Tumor BAI or CRAI index file cannot contain spaces and must have extension '.bai' or '.crai'",
```suggestion
                "errorMessage": "Tumor BAI or CRAI index file cannot contain spaces and must have extension '.bai', '.crai' or '.pbi'",
```

2024-11-21 07:53 UTC, fellen31 commented on assets/schema_input.json
> +                    }
Does this mean that the bam file is not requried, or why have anyOf?

2024-11-21 07:53 UTC, fellen31 commented on assets/schema_input.json
> +        "required": ["sample", "bam", "pbi"]
Should pbi always be required? Is it necessary if you have a file with unaligned reads?

2024-11-21 07:53 UTC, fellen31 commented on conf/test.config
> +        nextflow run nf-core/pacvario -profile test,<docker/singularity> --outdir <OUTDIR>
Pacvar or pacvario?

2024-11-21 07:53 UTC, fellen31 commented on conf/test.config
> +        cpus: 2,
```suggestion
        cpus: 4,
```

2024-11-21 07:53 UTC, fellen31 commented on conf/test.config
> +    input  = params.pipelines_testdata_base_path + 'refs/heads/pacvar/pacbio_data/samplesheet_longread_puretarget.csv'
Perhaps you could change the base of `pipelines_testdata_base_path` so that you can remove the first part of the path here and below? 
```suggestion
    input  = params.pipelines_testdata_base_path + 'pacbio_data/samplesheet_longread_puretarget.csv'
```

2024-11-21 07:53 UTC, fellen31 commented on conf/test.config
> +    id = 'C9ORF72'
Could this `id` be renamed to make it clearer what it refers to?

2024-11-21 07:53 UTC, fellen31 commented on conf/test_full.config
> +        cpus: 2,
```suggestion
        cpus: 4,
```

2024-11-21 07:53 UTC, fellen31 commented on conf/test_wgs_deepvariant.config
> +        cpus: 2,
```suggestion
        cpus: 4,
```

cpus could be 4 here and all other places.

2024-11-21 07:53 UTC, fellen31 commented on conf/test_wgs_deepvariant.config
> +    dbsnp_tbi = ''
If there are empty, perhaps they can be removed?

```suggestion
```

2024-11-21 07:53 UTC, fellen31 commented on conf/test_full.config
> +    intervals = params.pipelines_testdata_base_path + 'refs/heads/pacvar/pacbio_data/intervals.bed'
Could you align the `=`?

2024-11-21 07:53 UTC, fellen31 commented on conf/test_wgs_deepvariant.config
> +    input  = params.pipelines_testdata_base_path + 'refs/heads/pacvar/pacbio_data/subset_samplesheet_longread_puretarget.csv'
Could you align the `=` here as well, and in the other configs? 
Makes it easier to read.

2024-11-21 07:53 UTC, fellen31 commented on docs/output.md
> +  - `<sample>.<barcode-pair>.aligned.bam`: Aligned BAM
What if you skip barcode demuxing?

2024-11-21 07:53 UTC, fellen31 commented on docs/output.md
> +  - `<sample>.<barcode-pair>.sorted.bam.bai`: The indexed BAM file.
If you are using pbmm2, could you not sort and index the files with pbmm2?

2024-11-21 07:53 UTC, fellen31 commented on docs/output.md
> +  - `<sample>.<barcode-pair>.svsig.gz`: File containing signatures of structural variants
Does this need to be output?

2024-11-21 07:53 UTC, fellen31 commented on docs/output.md
> +  </details>
This does not look like the output from deepvariant

2024-11-21 07:53 UTC, fellen31 commented on docs/output.md
> +  - `<sample>.tsv`: A tsv listing bed files to merge with TAMA merge
Is this the only output from TRGT?

2024-11-21 07:53 UTC, fellen31 commented on docs/usage.md
> +| `bai`    | Path to the associated bai - bam index file. |
pbi?

2024-11-21 07:53 UTC, fellen31 commented on docs/usage.md
> +### Example SampleSheet
```suggestion
### Example samplesheet
```

2024-11-21 07:53 UTC, fellen31 commented on docs/usage.md
> +CONTROL_REP1, NA03697B2_02.bam,NA03697B2_03.pbi
```suggestion
CONTROL_REP1,NA03697B2_01.bam,NA03697B2_01.pbi
CONTROL_REP1,NA03697B2_02.bam,NA03697B2_02.pbi
```

2024-11-21 07:53 UTC, fellen31 commented on docs/usage.md
> +nextflow run nf-core/pacvar --input ./samplesheet.csv --outdir ./results --genome GRCh37 -profile docker --barcodes barcodes.fasta --intervals intervals.bed --workflow repeat --id repeat-id --tools '
Does this mean only one repeat is analysed at the time?

2024-11-21 07:53 UTC, fellen31 commented on main.nf
> +dbsnp_tbi = params.dbsnp_tbi ? Channel.fromPath(params.dbsnp_tbi).collect() : Channel.value([])
Could you align these.

2024-11-21 07:53 UTC, fellen31 commented on main.nf
> +id = params.id ? Channel.fromPath(params.id).map{ it -> [ [id:it.baseName], it ] }.collect() : Channel.empty()
align as well

2024-11-21 07:53 UTC, fellen31 commented on main.nf
> +    id
For someone not familiar with the code it's nice to have a comment that describes the inputs for all channels, not just samesheet (`// channel: samplesheet read in from --input`), e.g. https://github.com/nf-core/sarek/blob/5cc30494a6b8e7e53be64d308b582190ca7d2585/subworkflows/local/prepare_genome/main.nf#L31-L42

2024-11-21 07:53 UTC, fellen31 commented on modules/local/trgt/genotype.nf
Replace with nf-core module

2024-11-21 07:53 UTC, fellen31 commented on modules/local/trgt/plot.nf
Could also be replaced with nf-core module

2024-11-21 07:53 UTC, fellen31 commented on nextflow.config
> +    intervals                  = []
why is this [] and not null?

2024-11-21 07:53 UTC, fellen31 commented on nextflow.config
> +    // max_time                   = '240.h'
```suggestion
```

2024-11-21 07:53 UTC, fellen31 commented on nextflow.config
> +    version         = '0.1.0'
Most nf-core pipelines have 1.0 as their first release I believe. I'm not against 0.1.0, but do you have examples of other nf-core pipelines that have 0.* versions?

2024-11-21 07:53 UTC, fellen31 commented on nextflow_schema.json
> +                    "description": "Path to dbsnp"
Path to dbsnp what?

2024-11-21 07:53 UTC, fellen31 commented on nextflow_schema.json
> +                "tools": {
If the `tool` parameter is only to choose env-caller, could it be renamed? Tool is quite broad and it's not super clear which tools it refers to. Perhaps `--snv_caller`?

2024-11-21 07:53 UTC, fellen31 commented on nextflow_schema.json
> +                    "description": "variant calling tool - can either be deepvariant or gatk4"
Could you enforce that only deepvariant and gatk4 are viable input options?

2024-11-21 07:53 UTC, fellen31 commented on nextflow_schema.json
> +                    "description": "id for repeat"
Does this mean only one repeat is analysed per run? I imagine many users would be interested in analysing for example all repeats in a puratarget panel at the same time.

2024-11-21 07:53 UTC, fellen31 commented on nextflow_schema.json
> +                    "description": "Intervals for either varinat calling or for repeat expansion characterization"
How should this interval look?

2024-11-21 07:53 UTC, fellen31 commented on nextflow_schema.json
> +                    "description": "workflow type - can either be PureTarget or wgs"
Would it not be interesting to analyse repeats in WGS data as well?

2024-11-21 07:53 UTC, fellen31 commented on subworkflows/local/bam_snp_variant_calling/main.nf
> +        }
indent

2024-11-21 07:53 UTC, fellen31 commented on subworkflows/local/bam_snp_variant_calling/main.nf
> +    vcf_ch
Need to emit versions as well

2024-11-21 08:15 UTC, fellen31 commented on subworkflows/local/bam_snp_variant_calling/main.nf
> +    if (params.tools.split(',').contains('deepvariant')) {
is tools expected to take multiple tools? I.e., do you need split?

2024-11-21 08:15 UTC, fellen31 commented on subworkflows/local/bam_snp_variant_calling/main.nf
> +            [metadata, bam, bai, intervals]
```suggestion
            .map{meta, bam, bai ->
            [metadata, bam, bai, intervals]
```

2024-11-21 08:15 UTC, fellen31 commented on subworkflows/local/repeat_characterization/main.nf
> +                id)
Regarding my previous comment about id, I realise plotting many different repeat ID's might be challenging.

2024-11-21 08:15 UTC, fellen31 commented on subworkflows/local/set_value_channel.nf
> +// Check input samplesheet and get read channels
I don't really understand this workflow. You are working with bam-files, they do not need unzipping?

2024-11-21 08:15 UTC, fellen31 commented on workflows/pacvar.nf
> +include { TRGT_PLOT } from '../modules/local/trgt/plot'
align

2024-11-21 08:15 UTC, fellen31 commented on workflows/pacvar.nf
> +include { TRGT_PLOT } from '../modules/local/trgt/plot'
are these not used in the repeat subworkflow?

2024-11-21 08:15 UTC, fellen31 commented on workflows/pacvar.nf
> +include { HIPHASE as HIPHASE_SV} from '../modules/nf-core/hiphase/main'
Co-phasing SNPs and SVs would be nice later!

2024-11-21 08:15 UTC, fellen31 commented on workflows/pacvar.nf
> +            //seperate samples
see previous comment about `.map { meta, bam, bai ->  .... }`

2024-11-21 08:15 UTC, fellen31 commented on workflows/pacvar.nf
> +        PBMM2_ALIGN(pbmm2_ch, fasta)
I think you could restructure this code to just set the inputs to PBMM2_ALIGN in the if else block, and have PBMM2_ALIGN outside. (Also perhaps sort and index within pbmm2)

2024-11-21 08:15 UTC, fellen31 commented on workflows/pacvar.nf
> +    LIMA.out.bam
Should this be here?

2024-11-21 18:25 UTC, tanyasarkjain commented on README.md
> +![nf-core/rnaseq metro map](docs/images/metro_update_w_tabix_orange.svg)
yes! Thank you, no one has reviewed bits of the code before, and I have been committing directly to dev -- a maintainer assisted me in transferring the code to nf-core.

2024-11-21 18:26 UTC, tanyasarkjain commented on nextflow_schema.json
> +                    "description": "workflow type - can either be PureTarget or wgs"
It might be though I think if someone was interested in a repeat expansion they would opt for the PureTarget panel so they could get higher enrichment in that region - this is definitely something I could include in a later release.

2024-11-21 18:36 UTC, tanyasarkjain commented on workflows/pacvar.nf
> +include { HIPHASE as HIPHASE_SV} from '../modules/nf-core/hiphase/main'
Good point!

2024-11-21 21:29 UTC, tanyasarkjain commented on assets/schema_input.json
> +                    }
You're right - not needed

2024-11-21 21:45 UTC, tanyasarkjain commented on workflows/pacvar.nf
> +include { TRGT_PLOT } from '../modules/local/trgt/plot'
yes - an artifact from then I implemented the repeat functionality in pacvar.nf - will remove

2024-11-21 21:47 UTC, tanyasarkjain commented on docs/usage.md
> +nextflow run nf-core/pacvar --input ./samplesheet.csv --outdir ./results --genome GRCh37 -profile docker --barcodes barcodes.fasta --intervals intervals.bed --workflow repeat --id repeat-id --tools '
yes - for now, but I agree in later versions I'll work on making it analyze more than one repeat region

2024-11-21 22:04 UTC, tanyasarkjain commented on subworkflows/local/repeat_characterization/main.nf
> +                id)
yes - its something that's worth doing, but I'll leave it for a later release

2024-11-26 19:06 UTC, tanyasarkjain commented on docs/output.md
> +  - `<sample>.<barcode-pair>.sorted.bam.bai`: The indexed BAM file.
Yes - for now I will leave it as it accomplishes the same purpose

2024-11-26 20:07 UTC, tanyasarkjain commented on workflows/pacvar.nf
> +        PBMM2_ALIGN(pbmm2_ch, fasta)
done!

2024-11-26 20:08 UTC, tanyasarkjain commented on nextflow_schema.json
> +                    "description": "id for repeat"
Yes - I agree, but as you noted it's a bit complicated to implement. This is something I plan to complete in a later release

2024-11-26 20:09 UTC, tanyasarkjain commented on conf/test.config
> +    id = 'C9ORF72'
done!

2024-11-26 20:10 UTC, tanyasarkjain commented on docs/output.md
> +  - `<sample>.<barcode-pair>.svsig.gz`: File containing signatures of structural variants
Maybe not since it is an intermediate, but I'll output it anyway and let the user decide.

2024-11-26 20:10 UTC, tanyasarkjain commented on nextflow_schema.json
> +                "tools": {
done!

2024-11-26 20:13 UTC, tanyasarkjain commented on subworkflows/local/set_value_channel.nf
> +// Check input samplesheet and get read channels
That's true -- pulled it from a different workflows code and thought it didn't hurt to include, but it is un-needed so I have removed it.

2024-11-26 20:38 UTC, tanyasarkjain commented on subworkflows/local/bam_snp_variant_calling/main.nf
> +    if (params.tools.split(',').contains('deepvariant')) {
no, changed to reflect your suggestion

2024-11-26 22:55 UTC, tanyasarkjain commented on conf/test.config
> +    input  = params.pipelines_testdata_base_path + 'refs/heads/pacvar/pacbio_data/samplesheet_longread_puretarget.csv'
Linting fails if I change the testdata_base_path which is standardized across pipelines

2024-11-26 23:06 UTC, tanyasarkjain commented on docs/output.md
> +  - `<sample>.<barcode-pair>.aligned.bam`: Aligned BAM
fixed

2024-11-26 23:35 UTC, tanyasarkjain commented on conf/test_wgs_deepvariant.config
> +    dbsnp_tbi = ''
The default would be to stage the dbsnp associated with Genome, but for the purpose of these tests, that would take up additional memory + space and time to run, which is why Im manually setting it to no file so the variant calling can be run without a dbsnp file.

2024-11-28 09:46 UTC, fellen31 commented on conf/test.config
> +    input  = params.pipelines_testdata_base_path + 'refs/heads/pacvar/pacbio_data/samplesheet_longread_puretarget.csv'
I think you should be able to change it, see https://github.com/nf-core/methylseq/blob/d16f8f81e812d86f4d297e69de3f001628dfd5b4/nextflow.config#L102 for example.

2024-11-28 09:53 UTC, fellen31 commented on nextflow_schema.json
> +                    "description": "workflow type - can either be PureTarget or wgs"
I don't think that is always true. Someone might have a sample where they do not know what they are looking for beforehand, could for example be an SV, SNV or a repeat expansion. Sounds good to include in a future release.

2024-11-28 10:23 UTC, fellen31 reviewed
Nice, looking better! A few more comments 😊

2024-11-28 10:23 UTC, fellen31 commented on assets/schema_input.json
> +    "title": "nf-locate - params.input schema",
title should not include nf-locate I think.

2024-11-28 10:23 UTC, fellen31 commented on assets/schema_input.json
> +                "errorMessage": "Tumor BAM or CRAM file cannot contain spaces and must have extension '.bam' or '.cram'",
This is still unanswered.

2024-11-28 10:23 UTC, fellen31 commented on conf/test.config
> +    repeat_id                          = 'C9ORF72'
align

2024-11-28 10:23 UTC, fellen31 commented on conf/test_wgs_gatk.config
> +        cpus: 2,
```suggestion
        cpus: 4,
```

2024-11-28 10:23 UTC, fellen31 commented on docs/output.md
> +[SAMTOOLS](https://github.com/samtools/samtools) Sort and Index aligned bams.
```suggestion
[SAMTOOLS](https://github.com/samtools/samtools) Sort and index aligned bams.
```

2024-11-28 10:23 UTC, fellen31 commented on docs/output.md
> +  - `<basename>.vcf.gz`: Zipped VCF file -`<basename>.vcf.gz.tbi`: Associated index to zipped VCF file
Should be on multiple lines. Do you output the vcfstatsreport HTML as well?

2024-11-28 10:23 UTC, fellen31 commented on main.nf
>  include { PIPELINE_COMPLETION     } from './subworkflows/local/utils_nfcore_pacvar_pipeline'
```suggestion
include { PACVAR                  } from './workflows/pacvar'
include { PIPELINE_INITIALISATION } from './subworkflows/local/utils_nfcore_pacvar_pipeline'
include { PIPELINE_COMPLETION     } from './subworkflows/local/utils_nfcore_pacvar_pipeline'
```

2024-11-28 10:23 UTC, fellen31 commented on subworkflows/local/bam_snp_variant_calling/main.nf
> +                                    )
I think it would be easier to read the code if the indentation is consistent, if you keep this on the same level as line 21.

2024-11-28 10:23 UTC, fellen31 commented on subworkflows/local/bam_snp_variant_calling/main.nf
> +include { DEEPVARIANT_RUNDEEPVARIANT } from '../../../modules/nf-core/deepvariant/rundeepvariant/main'
```suggestion
include { GATK4_HAPLOTYPECALLER      } from '../../../modules/nf-core/gatk4/haplotypecaller/main'
include { DEEPVARIANT_RUNDEEPVARIANT } from '../../../modules/nf-core/deepvariant/rundeepvariant/main'
```

2024-11-28 10:23 UTC, fellen31 commented on subworkflows/local/bam_sv_variant_calling/main.nf
> +include { TABIX_BGZIP } from '../../../modules/nf-core/tabix/bgzip/main'
could you align here as well? And the other subworkflows.

2024-11-28 10:23 UTC, fellen31 commented on subworkflows/local/repeat_characterization/main.nf
> +    //                 bed)
I don't think this should be here. 
```suggestion
```

2024-11-28 10:23 UTC, fellen31 commented on subworkflows/local/repeat_characterization/main.nf
> +    //             repeat_id)
same here.

2024-11-28 10:23 UTC, fellen31 commented on subworkflows/local/repeat_characterization/main.nf
> +
```suggestion
```

2024-11-28 10:23 UTC, fellen31 commented on subworkflows/local/repeat_characterization/main.nf
> +    bam_bai_ch = SAMTOOLS_SORT.out.bam.join(SAMTOOLS_INDEX.out.bai).view()
`.view()` should not be here.

2024-11-28 10:23 UTC, fellen31 commented on subworkflows/local/set_value_channel.nf
> +// Check input samplesheet and get read channels
Still don't understand why this needs to be a subworkflow at all.

2024-11-28 10:23 UTC, fellen31 commented on workflows/pacvar.nf
> +                        fasta)
Could you indent these on the same level as well? See for example https://github.com/nf-core/methylseq/blob/master/workflows/methylseq/main.nf.

2024-11-28 10:23 UTC, fellen31 commented on workflows/pacvar.nf
Could you indent the inputs to processes/subworkflows on the same level? See for example https://github.com/nf-core/methylseq/blob/master/workflows/methylseq/main.nf.

2024-11-28 10:23 UTC, fellen31 commented on workflows/pacvar.nf
>      ch_versions = Channel.empty()
You need to collect the versions from each from each workflow/process into this channel.  So `ch_versions = Channel.empty()` needs to be at the top of the workflow, and then as you did in the subworkflows, e.g.  `ch_versions = ch_versions.mix(TRGT_GENOTYPE.out.versions)`

2024-11-29 06:29 UTC, tanyasarkjain commented on workflows/pacvar.nf
> +                        fasta)
fixed so arguments are one tab from the start of the function

2024-11-29 06:34 UTC, tanyasarkjain commented on workflows/pacvar.nf
>      ch_versions = Channel.empty()
resolved!

2024-11-29 12:18 UTC, sateeshperi requested changes
fix test profile

2024-11-29 14:15 UTC, fellen31 commented
Still some unanswered questions/comments.

2024-11-29 18:45 UTC, tanyasarkjain commented on assets/schema_input.json
> +                "errorMessage": "Tumor BAM or CRAM file cannot contain spaces and must have extension '.bam' or '.cram'",
Apologies, thought I changed  the error message previously so that it no longer included "Tumor"

2024-11-29 18:46 UTC, tanyasarkjain commented on assets/schema_input.json
> +                "errorMessage": "Tumor BAI or CRAI index file cannot contain spaces and must have extension '.bai' or '.crai'",
no

2024-11-29 18:47 UTC, tanyasarkjain commented on assets/schema_input.json
> +        "required": ["sample", "bam", "pbi"]
changed so not required

2024-11-29 18:47 UTC, tanyasarkjain commented on conf/test.config
> +        nextflow run nf-core/pacvario -profile test,<docker/singularity> --outdir <OUTDIR>
fixed

2024-11-29 18:48 UTC, tanyasarkjain commented on conf/test.config
> +    input  = params.pipelines_testdata_base_path + 'refs/heads/pacvar/pacbio_data/samplesheet_longread_puretarget.csv'
maybe it is because I included refs/heads - will try with just pacvar

2024-11-29 18:50 UTC, tanyasarkjain commented on docs/output.md
> +  </details>
fixed!

2024-11-29 18:51 UTC, tanyasarkjain commented on docs/output.md
> +  - `<sample>.tsv`: A tsv listing bed files to merge with TAMA merge
fixed

2024-11-29 18:52 UTC, tanyasarkjain commented on nextflow_schema.json
> +                    "description": "workflow type - can either be PureTarget or wgs"
True!

2024-11-29 18:54 UTC, tanyasarkjain commented on docs/output.md
> +  - `<basename>.vcf.gz`: Zipped VCF file -`<basename>.vcf.gz.tbi`: Associated index to zipped VCF file
No - I do not currently output the vcf stats report html

2024-12-01 05:02 UTC, sateeshperi commented
Things to do;
* Update nf-core subworkflows
* Update docs/usage.md & docs/output.md
* Make a proper `test_full` samplesheet (currently uses the same as test profile)

2024-12-19 02:09 UTC, sateeshperi commented on docs/usage.md
> +Each sample cooresponds to a different run on PacBio revio machines. Each sample will (if not skipping demultiplexing) proceed to be demultiplexed according to the inputted --barcodes barcodes.fasta,
```suggestion
Each sample corresponds to a different run on PacBio revio machines. Each sample will (if not skipping demultiplexing) will be demultiplexed according to the input `barcodes.fasta`, therefore each sample in the samplesheet should have the same adapters.
```

2024-12-24 05:03 UTC, sateeshperi commented on README.md
> +nf-core/pacvar is a bioinformatics pipeline that processes long read pacbio data. Specifically the pipeline contains two workflows, one to process whole genome sequence data and other to process read
```suggestion
nf-core/pacvar is a bioinformatics pipeline that processes long-read PacBio data. Specifically, the pipeline provides two workflows: one for processing whole-genome sequencing data, and another for processing reads from the PureTarget expansion panel offered by PacBio. This second workflow characterizes tandem repeats. Because the pipeline is designed for PacBio reads, it uses PacBio’s officially released tools.
```

2024-12-24 05:03 UTC, sateeshperi commented on README.md
> +1. Demultiplex reads ([`lima`](https://lima.how))
```suggestion
Workflow Overview

1. Demultiplex reads ([`lima`](https://lima.how))
```

2024-12-24 05:03 UTC, sateeshperi commented on README.md
>  wgs workflow
```suggestion
WGS Workflow Overview
```

2024-12-24 05:03 UTC, sateeshperi commented on README.md
>  repeat workflow
```suggestion
Tandem Repeat Workflow Overview
```

2024-12-24 05:03 UTC, sateeshperi commented on README.md
> +Note the pbi is not required in which case the input would look like this:
```suggestion
Note that the `.pbi` file is not required. If you choose not to include it, your input file might look like this:
```

2024-12-24 05:03 UTC, sateeshperi commented on README.md
> +optional paramaters include: --skip_demultiplexing, --skip_snp, --skip_sv, --skip_phase
```suggestion
optional paramaters include: `--skip_demultiplexing`, `--skip_snp`, `--skip_sv`, `--skip_phase`.
```

2024-12-24 05:03 UTC, sateeshperi commented on assets/samplesheet.csv
> +sample1,/path/to/bam/file/AEG588A1_1.bam,/path/to/bai/file/AEG588A1_1.pbi
provide actual test data github links here

2024-12-24 05:03 UTC, sateeshperi commented on docs/output.md
> +When --skip_demultiplexing false (default behavior)
```suggestion
When `--skip_demultiplexing` is false (default behavior)
```

2024-12-24 05:03 UTC, sateeshperi commented on docs/output.md
> +  - `<sample>.lima.report`: Tab-separated file about each ZMW, unfiltered
what is ZMW ? provide full-form

2024-12-24 05:03 UTC, sateeshperi commented on docs/output.md
> +- If --skip_demultiplexing true
```suggestion
- If `--skip_demultiplexing` is true:
```

2024-12-24 05:03 UTC, sateeshperi commented on docs/output.md
> +- If --skip_demultiplexing false
```suggestion
- If `--skip_demultiplexing` is false:
```

2024-12-24 05:03 UTC, sateeshperi commented on docs/output.md
> +  - `<basename>.svg`: Waterfall plot of the repeat region
will you be able to add screenshots/images of these plots from test run to show how these plots will look like ?

2024-12-24 05:03 UTC, sateeshperi commented on docs/usage.md
> +This pipeline has been designed to analyze multiple runs, gathering its input from a provided samplesheet.
```suggestion
The nf-core/pacvar pipeline has been designed to analyze data from multiple runs, gathering its input from a provided samplesheet.
```

2024-12-24 05:03 UTC, sateeshperi commented on docs/usage.md
> +
```suggestion
```

The typical command for running the pipeline is as follows for the repeat workflow:

```
```

2024-12-24 05:03 UTC, sateeshperi commented on docs/usage.md
> +The typical command for running the pipeline is as follows for the wgs and the repeat workflow:
```suggestion
The typical command for running the pipeline is as follows for the wgs workflow:
```

2024-12-24 05:03 UTC, sateeshperi commented on docs/usage.md
> +nextflow run nf-core/pacvar --input ./samplesheet.csv --outdir ./results --genome 'GATK.GRCh38' -profile docker --barcodes barcodes.fasta --intervals intervals.bed --workflow wgs --snv_caller deepvar
```suggestion
nextflow run nf-core/pacvar --input ./samplesheet.csv --outdir ./results --genome 'GATK.GRCh38' -profile <docker/singularity/conda> --barcodes barcodes.fasta --intervals intervals.bed --workflow wgs --snv_caller deepvariant
```

2024-12-24 05:03 UTC, sateeshperi commented on docs/usage.md
> +nextflow run nf-core/pacvar --input ./samplesheet.csv --outdir ./results --genome  'GATK.GRCh38' -profile docker --barcodes barcodes.fasta --intervals intervals.bed --workflow repeat --repeat_id repe
```suggestion
nextflow run nf-core/pacvar --input ./samplesheet.csv --outdir ./results --genome  'GATK.GRCh38' -profile <docker/singularity/conda> --barcodes barcodes.fasta --intervals intervals.bed --workflow repeat --repeat_id repeat-id --snv_caller 'deepvariant'
```

2024-12-24 05:03 UTC, sateeshperi commented on docs/usage.md
>  This will launch the pipeline with the `docker` configuration profile. See below for more information about profiles.
```suggestion
> See below for more information about profiles.
```

2024-12-24 05:58 UTC, tanyasarkjain commented on docs/output.md
> +  - `<basename>.svg`: Waterfall plot of the repeat region
Sure

2025-01-28 06:07 UTC, sateeshperi commented on CHANGELOG.md
> +## v0.1.0 - [date]
Update Date before release

2025-01-28 06:07 UTC, sateeshperi approved these changes

2025-01-31 01:28 UTC, charles-plessy requested changes
Is the `out` directory needed or was it committed by accident?

2025-01-31 01:28 UTC, charles-plessy commented on CHANGELOG.md
> +## v1.0.0 - [date]
Please add the date and consider a release name (see near <https://nf-co.re/docs/contributing/release_checklist#steps-to-release>)

2025-01-31 01:28 UTC, charles-plessy commented on CITATIONS.md
> +- [deepvariant](https://www.nature.com/articles/nbt.4235)
How about https://pubmed.ncbi.nlm.nih.gov/30247488/ for consistency?

2025-01-31 01:28 UTC, charles-plessy commented on README.md
> +[![Nextflow](https://img.shields.io/badge/nextflow%20DSL2-%E2%89%A524.04.2-23aa62.svg)](https://www.nextflow.io/)
Looks like a duplicated line.

2025-01-31 01:28 UTC, charles-plessy commented on docs/usage.md
> +| `bam`    | Path to the unaligned bam file`.                        |
Typo: extra ` character after file.

2025-01-31 01:28 UTC, charles-plessy commented on README.md
> +<!-- TODO nf-core: Describe the minimum required steps to execute the pipeline, e.g. how to prepare samplesheets.
Please address this TODO point.  You can see examples of other pipelines, like https://nf-co.re/rnaseq/3.18.0

2025-01-31 01:28 UTC, charles-plessy commented on nextflow.config
> +    version         = '0.1.0'
I also think it should be 1.0.0: https://semver.org/#how-do-i-know-when-to-release-100

2025-01-31 01:28 UTC, charles-plessy commented on nextflow_schema.json
> +        "variant": {
Please consider adding "fa_icon" everywhere. The web interface of `nf-core pipelines schema build` can help a lot with this.

2025-01-31 01:28 UTC, charles-plessy commented on nextflow_schema.json
> +                    "description": "variant calling tool - can either be deepvariant or gatk4"
Please maintain consistency of upper-case use on first letters of descriptions.

2025-01-31 01:28 UTC, charles-plessy commented on nextflow_schema.json
> +                    "description": "workflow type - can either be PureTarget or wgs"
How about using an `enum` here?

2025-01-31 20:31 UTC, tanyasarkjain commented on nextflow.config
> +    version         = '0.1.0'
Resolved!

2025-01-31 20:34 UTC, tanyasarkjain commented on CHANGELOG.md
> +## v1.0.0 - [date]
resolved!

2025-01-31 20:34 UTC, tanyasarkjain commented on CITATIONS.md
> +- [deepvariant](https://www.nature.com/articles/nbt.4235)
changed

2025-01-31 20:35 UTC, tanyasarkjain commented on README.md
> +[![Nextflow](https://img.shields.io/badge/nextflow%20DSL2-%E2%89%A524.04.2-23aa62.svg)](https://www.nextflow.io/)
fixed

2025-01-31 20:36 UTC, tanyasarkjain commented on docs/usage.md
> +| `bam`    | Path to the unaligned bam file`.                        |
fixed

2025-01-31 20:36 UTC, tanyasarkjain commented on nextflow.config
> +    version         = '0.1.0'
fixed

2025-01-31 22:17 UTC, tanyasarkjain commented on nextflow_schema.json
> +                    "description": "workflow type - can either be PureTarget or wgs"
done

2025-01-31 22:19 UTC, tanyasarkjain commented on nextflow_schema.json
> +                    "description": "variant calling tool - can either be deepvariant or gatk4"
fixed

2025-01-31 22:29 UTC, tanyasarkjain commented on README.md
> +<!-- TODO nf-core: Describe the minimum required steps to execute the pipeline, e.g. how to prepare samplesheets.
Thank you - I actually explain how to do this after this comment in the README (for instance I give an example samplesheet) - I just forgot to remove this comment

2025-01-31 22:53 UTC, tanyasarkjain commented on nextflow_schema.json
> +        "variant": {
resolved

2025-01-31 23:52 UTC, charles-plessy approved these changes
Looks good to me!

2025-02-04 18:30 UTC, merged